# -*- coding: utf-8 -*-
"""CICIDS-2017.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkXKu7PU1L-Ua6NpNWYW-o22P2V5dDHu
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

files = [
    "/content/drive/MyDrive/monday[1].csv",
    "/content/drive/MyDrive/thursday[1].csv",
    "/content/drive/MyDrive/monday_plus[1].csv",
    "/content/drive/MyDrive/tuesday[1].csv",
    "/content/drive/MyDrive/thursday_plus[1].csv",
    "/content/drive/MyDrive/tuesday_plus[1].csv",
    "/content/drive/MyDrive/wednesday[1].csv",
    "/content/drive/MyDrive/friday[1].csv",
    "/content/drive/MyDrive/friday_plus[1].csv",
    "/content/drive/MyDrive/wednesday_plus[1].csv"
]

dfs = []

for f in files:
    dfs.append(pd.read_csv(f, nrows=50000))  # load only 50k rows per CSV

# Combine all samples
df = pd.concat(dfs, ignore_index=True)
print("Combined dataset shape:", df.shape)
df.head()

import numpy as np

df = df.dropna()                      # remove missing values
df = df.replace([np.inf, -np.inf], 0) # replace infinite values

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Label'] = le.fit_transform(df['Label'])  # BENIGN=0, ATTACK=1

X = df.drop("Label", axis=1)
y = df["Label"]

from sklearn.preprocessing import MinMaxScaler

# Keep only numeric columns
X_numeric = X.select_dtypes(include='number')

print("Columns used for scaling:", X_numeric.columns)

# Scale numeric features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_numeric)

X = X_scaled  # now X is numeric and safe for ANN/CNN

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.utils import class_weight
import numpy as np

# Compute class weights
class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)
class_weights_dict = dict(enumerate(class_weights))

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D, Flatten, Dropout, Reshape

# Reshape input for Conv1D: (samples, features, 1)
X_train_cnn = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test_cnn = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

model_cnn = Sequential([
    Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_train.shape[1],1)),
    Dropout(0.3),
    Conv1D(32, kernel_size=3, activation='relu'),
    Dropout(0.2),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.2),
    Dense(len(np.unique(y_train)), activation='softmax')  # multiclass
])

model_cnn.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

history = model_cnn.fit(
    X_train_cnn, y_train,
    epochs=30, batch_size=64,
    validation_split=0.2,
    class_weight=class_weights_dict
)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

y_pred = model_cnn.predict(X_test_cnn).argmax(axis=1)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", cm)